spring:
  application:
    name: Mock Server
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

management:
  server:
    port: 8090
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,info,env,git,h2-console'