spring:
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: beeceptor
          uri: https://arvinds-test.free.beeceptor.com
          predicates:
            - Path=/beeceptor/**

management:
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'