spring:
  mvc:
    problemdetails:
      enabled: true
  r2dbc:
    initialization-mode: always
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  h2.console:
    # Required for h2-console server
    enabled: true
  datasource:
    url: r2dbc:h2:file:./test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: beeceptor
          uri: https://arvinds-test.free.beeceptor.com
          predicates:
            - Path=/beeceptor/**

management:
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: 'health,info,env,git,h2console'
